---
- name: Deploy MERN App to Kubernetes Cluster
  hosts: localhost
  tasks:
    - name: Apply MongoDB Manifest
      kubernetes.core.k8s:
        src: ./k8s/mongodb.yaml
        state: present

    - name: Apply Backend Application Manifest
      kubernetes.core.k8s:
        src: ./k8s/backend.yaml
        state: present

    - name: Apply Frontend Application Manifest
      kubernetes.core.k8s:
        src: ./k8s/frontend.yaml
        state: present